/*
 * License for the BOLOS User Interface Library project, originally found here:
 * https://github.com/parkerhoyes/bolos-user-interface
 *
 * Copyright (C) 2016, 2017 Parker Hoyes <contact@parkerhoyes.com>
 *
 * This software is provided "as-is", without any express or implied warranty.
 * In no event will the authors be held liable for any damages arising from the
 * use of this software.
 *
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 *
 * 1. The origin of this software must not be misrepresented; you must not claim
 *    that you wrote the original software. If you use this software in a
 *    product, an acknowledgment in the product documentation would be
 *    appreciated but is not required.
 * 2. Altered source versions must be plainly marked as such, and must not be
 *    misrepresented as being the original software.
 * 3. This notice may not be removed or altered from any source distribution.
 */


#ifndef BUI_FONT_EXCLUDE_COMIC_SANS_MS_20
#include "fonts/bui_font_comic_sans_ms_20.inc"
const bui_font_t bui_font_comic_sans_ms_20 = &bui_font_data_comic_sans_ms_20;
#else
const bui_font_t bui_font_comic_sans_ms_20 = NULL;
#endif

#ifndef BUI_FONT_EXCLUDE_LUCIDA_CONSOLE_8
#include "fonts/bui_font_lucida_console_8.inc"
const bui_font_t bui_font_lucida_console_8 = &bui_font_data_lucida_console_8;
#else
const bui_font_t bui_font_lucida_console_8 = NULL;
#endif

#ifndef BUI_FONT_EXCLUDE_LUCIDA_CONSOLE_15
#include "fonts/bui_font_lucida_console_15.inc"
const bui_font_t bui_font_lucida_console_15 = &bui_font_data_lucida_console_15;
#else
const bui_font_t bui_font_lucida_console_15 = NULL;
#endif

#ifndef BUI_FONT_EXCLUDE_OPEN_SANS_BOLD_13
#include "fonts/bui_font_open_sans_bold_13.inc"
const bui_font_t bui_font_open_sans_bold_13 = &bui_font_data_open_sans_bold_13;
#else
const bui_font_t bui_font_open_sans_bold_13 = NULL;
#endif

#ifndef BUI_FONT_EXCLUDE_OPEN_SANS_BOLD_21
#include "fonts/bui_font_open_sans_bold_21.inc"
const bui_font_t bui_font_open_sans_bold_21 = &bui_font_data_open_sans_bold_21;
#else
const bui_font_t bui_font_open_sans_bold_21 = NULL;
#endif

#ifndef BUI_FONT_EXCLUDE_OPEN_SANS_EXTRABOLD_11
#include "fonts/bui_font_open_sans_extrabold_11.inc"
const bui_font_t bui_font_open_sans_extrabold_11 = &bui_font_data_open_sans_extrabold_11;
#else
const bui_font_t bui_font_open_sans_extrabold_11 = NULL;
#endif

#ifndef BUI_FONT_EXCLUDE_OPEN_SANS_LIGHT_13
#include "fonts/bui_font_open_sans_light_13.inc"
const bui_font_t bui_font_open_sans_light_13 = &bui_font_data_open_sans_light_13;
#else
const bui_font_t bui_font_open_sans_light_13 = NULL;
#endif

#ifndef BUI_FONT_EXCLUDE_OPEN_SANS_LIGHT_14
#include "fonts/bui_font_open_sans_light_14.inc"
const bui_font_t bui_font_open_sans_light_14 = &bui_font_data_open_sans_light_14;
#else
const bui_font_t bui_font_open_sans_light_14 = NULL;
#endif

#ifndef BUI_FONT_EXCLUDE_OPEN_SANS_LIGHT_16
#include "fonts/bui_font_open_sans_light_16.inc"
const bui_font_t bui_font_open_sans_light_16 = &bui_font_data_open_sans_light_16;
#else
const bui_font_t bui_font_open_sans_light_16 = NULL;
#endif

#ifndef BUI_FONT_EXCLUDE_OPEN_SANS_LIGHT_20
#include "fonts/bui_font_open_sans_light_20.inc"
const bui_font_t bui_font_open_sans_light_20 = &bui_font_data_open_sans_light_20;
#else
const bui_font_t bui_font_open_sans_light_20 = NULL;
#endif

#ifndef BUI_FONT_EXCLUDE_OPEN_SANS_LIGHT_21
#include "fonts/bui_font_open_sans_light_21.inc"
const bui_font_t bui_font_open_sans_light_21 = &bui_font_data_open_sans_light_21;
#else
const bui_font_t bui_font_open_sans_light_21 = NULL;
#endif

#ifndef BUI_FONT_EXCLUDE_OPEN_SANS_LIGHT_32
#include "fonts/bui_font_open_sans_light_32.inc"
const bui_font_t bui_font_open_sans_light_32 = &bui_font_data_open_sans_light_32;
#else
const bui_font_t bui_font_open_sans_light_32 = NULL;
#endif

#ifndef BUI_FONT_EXCLUDE_OPEN_SANS_REGULAR_11
#include "fonts/bui_font_open_sans_regular_11.inc"
const bui_font_t bui_font_open_sans_regular_11 = &bui_font_data_open_sans_regular_11;
#else
const bui_font_t bui_font_open_sans_regular_11 = NULL;
#endif

#ifndef BUI_FONT_EXCLUDE_OPEN_SANS_SEMIBOLD_18
#include "fonts/bui_font_open_sans_semibold_18.inc"
const bui_font_t bui_font_open_sans_semibold_18 = &bui_font_data_open_sans_semibold_18;
#else
const bui_font_t bui_font_open_sans_semibold_18 = NULL;
#endif
